---
#
# Ansible managed
#
repository:
  description: Kibana for Linux.
  homepage: https://buluma.github.io/
  topics: web, system, monitoring, kibana, elk, efk, logging, dataviz, ansible, molecule, tox, playbook
