---
- name: Converge
  hosts: all
  become: true
  gather_facts: true
  pre_tasks:
    - ansible.builtin.apt:
        cache_valid_time: 600
        update_cache: true
      name: Update apt cache.
      when: ansible_facts['os_family'] == 'Debian'
  roles:
    - role: buluma.kibana
